language: csharp
mono: none
dotnet: 2.1.4
before_install:
  - git clone --depth=50 --branch=master https://github.com/Halcyon-Core/Halcyon-Heart.git /home/travis/build/Halcyon-Core/Halcyon-Heart
  - git clone --depth=50 --branch=master https://github.com/Halcyon-Core/Halcyon-Identity.git /home/travis/build/Halcyon-Core/Halcyon-Identity
  - cd src/Halcyon.Cms.Web.Mvc
script:
  - dotnet restore
  - dotnet build
